apiVersion: v1
kind: Template
metadata:
  name: postgresql-template
  annotations:
    description: "Creating PostgreSQL database"
    iconClass: "iconpostgresql"
    tags: "database,sql"
parameters:
  - description: PostgreSQL image to use
    name: POSTGRESQL_IMAGE
    value: registry.access.redhat.com/rhscl/postgresql-10-rhel7:latest
labels:
  template: "postgresql"
objects:
  - apiVersion: v1
    kind: Secret
    metadata:
      name: postgresql
    type: Opaque
    stringData:
      database-name: test
      username: test
      password: test
  # non-production ready deployment of PostgreSQL to show WildFly quickstarts capabilities
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      name: postgresql
      labels:
        app: postgresql
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: postgresql
      template:
        metadata:
          labels:
            app: postgresql
        spec:
          containers:
            - name: postgresql
              image: ${POSTGRESQL_IMAGE}
              ports:
                - containerPort: 5432
              env:
                - name: POSTGRESQL_DATABASE
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: postgresql
                - name: POSTGRESQL_USER
                  valueFrom:
                    secretKeyRef:
                      key: username
                      name: postgresql
                - name: POSTGRESQL_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: password
                      name: postgresql
                - name: POSTGRESQL_MAX_PREPARED_TRANSACTIONS
                  value: "42"
  - apiVersion: v1
    kind: Service
    metadata:
      name: postgresql
    spec:
      selector:
        app: postgresql
      ports:
        - protocol: TCP
          port: 5432
          targetPort: 5432
